/**
 * Formatter for the `.d.ts` file that `kmagent types` emits.
 *
 * The kernel doesn't currently ship real type signatures over the
 * wire — only the list of export names from `getApiSurface()`. This
 * module turns that list into a TypeScript declaration that lets
 * authors `import { useRepo, defineProperty, … } from '@/extensions/
 * api.js'` and have the editor / type-checker resolve the imports,
 * even though the symbols are typed `any` for now.
 *
 * The "real types" upgrade path would be a separate command that
 * fetches an actual .d.ts produced by the host app's build; that
 * shape will swap in here without callers noticing.
 */

/** A JS identifier — what `Object.keys(apiModule)` returns. Validated
 *  conservatively (the runtime would already reject malformed names,
 *  but we double-check so a hostile or buggy bridge can't make us emit
 *  syntactically invalid .d.ts). */
const isValidIdentifier = (name: string): boolean =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)

export interface KernelDtsOptions {
  /** The module specifier authors import from — typically
   *  `@/extensions/api.js`. */
  moduleSpec: string
  /** Sorted list of exported binding names from the kernel API. */
  exports: readonly string[]
  /** Version of the CLI that emitted the file; shows up in the
   *  header comment so users can tell whether a refresh is needed. */
  cliVersion: string
  /** Optional ISO timestamp embedded in the header. Defaults to the
   *  current time. Parameter exists so tests can pin the output. */
  generatedAt?: string
}

const HEADER = (cliVersion: string, generatedAt: string, moduleSpec: string) =>
  `// ----------------------------------------------------------------------------
// Generated by \`kmagent types\` (CLI v${cliVersion}) at ${generatedAt}.
//
// Re-run after updating the host app to refresh the list of exports.
//
// These are *marker* declarations: importing a symbol from
// \`${moduleSpec}\` will type-check and resolve, but the symbol is
// typed as \`any\` here — the host app's actual signatures remain the
// source of truth. Hover into the source via your editor's "go to
// definition" or check \`kmagent describe-runtime --guide <topic>\`
// when you need real shapes.
// ----------------------------------------------------------------------------
`

/** Render the .d.ts contents. Pure function — no I/O. */
export const renderKernelDts = (options: KernelDtsOptions): string => {
  const generatedAt = options.generatedAt ?? new Date().toISOString()
  const safeExports = options.exports
    .filter(name => isValidIdentifier(name))
    // Deduplicate — `getApiSurface` already returns a sorted unique
    // list, but a defensive dedup makes the formatter robust to
    // malformed input.
    .filter((name, i, arr) => arr.indexOf(name) === i)

  const declLines = safeExports
    .map(name => `  export const ${name}: any`)
    .join('\n')

  const primary = `declare module '${options.moduleSpec}' {
${declLines}
}`

  // Also declare the no-`.js` form so authors who write
  // `import {…} from '@/extensions/api'` (without the suffix) get
  // resolution. This is a thin re-export of the primary module.
  const stripJs = options.moduleSpec.endsWith('.js')
    ? options.moduleSpec.slice(0, -3)
    : null
  const alias = stripJs
    ? `declare module '${stripJs}' {
  export * from '${options.moduleSpec}'
}
`
    : ''

  return `${HEADER(options.cliVersion, generatedAt, options.moduleSpec)}
${primary}
${alias ? `\n${alias}` : ''}`
}
