// Render powersync/sync-config.yaml from the TS column lists in
// blockSchema/workspaceSchema. The local-SQLite raw-table mapping and
// the PowerSync sync-stream SELECT must project the same columns or
// rows arrive without the missing fields and clients silently read
// defaults — see feedback_powersync_sync_config_with_schema. Driving
// both from the same TS arrays makes that drift structurally impossible.
//
// Run via `yarn gen:sync-config` after editing the column lists, or
// `yarn check:sync-config` (no writes) to fail CI on hand-edits to the
// generated YAML.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { BLOCK_STORAGE_COLUMNS } from '@/data/blockSchema'
import {
  WORKSPACE_COLUMNS,
  WORKSPACE_MEMBER_COLUMNS,
} from '@/data/workspaceSchema'

interface StreamQuery {
  // Public-schema-qualified table the SELECT reads from. Also drives
  // the column prefix (e.g. `public.blocks` → `blocks.<col>`).
  readonly table: `public.${string}`
  readonly columns: readonly { readonly name: string }[]
  // WHERE clause that scopes the table to the workspaces the requesting
  // user belongs to. Already indented to match the YAML body.
  readonly predicate: string
}

const STREAM_QUERIES: readonly StreamQuery[] = [
  {
    table: 'public.workspaces',
    columns: WORKSPACE_COLUMNS,
    predicate: '        WHERE workspaces.id IN user_workspaces',
  },
  {
    table: 'public.workspace_members',
    columns: WORKSPACE_MEMBER_COLUMNS,
    predicate: '        WHERE workspace_members.workspace_id IN user_workspaces',
  },
  {
    table: 'public.blocks',
    columns: BLOCK_STORAGE_COLUMNS,
    predicate: '        WHERE blocks.workspace_id IN user_workspaces',
  },
] as const

const HEADER =
`# DO NOT EDIT — generated by scripts/gen-sync-config.ts.
# Run \`yarn gen:sync-config\` after editing the column lists in
# src/data/blockSchema.ts or src/data/workspaceSchema.ts.
# CI runs \`yarn check:sync-config\` to catch hand-edits.
#
# One auto-subscribed stream scoped to the requesting user's workspaces.
# Grouping the related tables into one stream keeps the client subscription
# surface and bucket count smaller than three independent auto streams.
# PowerSync re-evaluates the set whenever workspace_members changes.
#
# IMPORTANT: do not alias the primary table in the FROM clause. PowerSync uses
# the FROM-clause name as the row_type that maps back to the client's raw
# table name. \`FROM public.blocks b\` would surface row_type='b' and the
# client would never hydrate its \`blocks\` table.
#
# workspace_invitations is intentionally NOT synced. Invitations are queried
# on demand via Supabase REST + the workspace_invitations RLS policy keyed
# on auth.email(); putting the email claim into a sync rule would require
# threading the JWT through PowerSync's parameter system, and invitations
# are low-frequency events so polling on login is fine.

config:
  edition: 3

streams:
`

const renderQuery = ({ table, columns, predicate }: StreamQuery): string => {
  const tableShortName = table.replace(/^public\./, '')
  const projection = columns
    .map((c) => `          ${tableShortName}.${c.name}`)
    .join(',\n')
  return `      - |
        SELECT
${projection}
        FROM ${table}
${predicate}
`
}

const renderStream = (): string => `  workspace_data:
    auto_subscribe: true
    with:
      user_workspaces: |
        SELECT workspace_id
        FROM public.workspace_members
        WHERE user_id = auth.user_id()
    queries:
${STREAM_QUERIES.map(renderQuery).join('')}
`

const generated = HEADER + renderStream()

const here = dirname(fileURLToPath(import.meta.url))
const targetPath = resolve(here, '..', 'powersync', 'sync-config.yaml')
const isCheck = process.argv.includes('--check')

const rel = relative(process.cwd(), targetPath)

if (isCheck) {
  const existing = existsSync(targetPath) ? readFileSync(targetPath, 'utf-8') : ''
  if (existing !== generated) {
    console.error(
      `❌ ${rel} is stale. Run \`yarn gen:sync-config\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`✓ ${rel} is up to date.`)
} else {
  writeFileSync(targetPath, generated)
  console.log(`Wrote ${rel}.`)
}
