// Render powersync/sync-config.yaml from the TS column lists in
// blockSchema/workspaceSchema. The local-SQLite raw-table mapping and
// the PowerSync sync-stream SELECT must project the same columns or
// rows arrive without the missing fields and clients silently read
// defaults — see feedback_powersync_sync_config_with_schema. Driving
// both from the same TS arrays makes that drift structurally impossible.
//
// Run via `pnpm gen:sync-config` after editing the column lists, or
// `pnpm check:sync-config` (no writes) to fail CI on hand-edits to the
// generated YAML.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { BLOCK_STORAGE_COLUMNS } from '@/data/blockSchema'
import {
  WORKSPACE_COLUMNS,
  WORKSPACE_MEMBER_COLUMNS,
} from '@/data/workspaceSchema'

interface StreamQuery {
  // Public-schema-qualified table the SELECT reads from. Also drives
  // the column prefix (e.g. `public.blocks` → `blocks.<col>`).
  readonly table: `public.${string}`
  // Optional FROM-clause alias. PowerSync derives the client-side
  // row_type from the FROM-clause name, so an alias re-emits the same
  // physical table under a DIFFERENT row_type. Used only for the Layout B
  // `blocks_synced` twin below; leave unset to surface `row_type = table`.
  readonly as?: string
  readonly columns: readonly { readonly name: string }[]
  // WHERE clause that scopes the table to the workspaces the requesting
  // user belongs to. Already indented to match the YAML body.
  readonly predicate: string
}

const STREAM_QUERIES: readonly StreamQuery[] = [
  {
    table: 'public.workspaces',
    columns: WORKSPACE_COLUMNS,
    predicate: '        WHERE workspaces.id IN user_workspaces',
  },
  {
    table: 'public.workspace_members',
    columns: WORKSPACE_MEMBER_COLUMNS,
    predicate: '        WHERE workspace_members.workspace_id IN user_workspaces',
  },
  {
    // Layout B blocks stream (cutover complete). Re-emits `public.blocks`
    // under row_type `blocks_synced` (PowerSync derives row_type from the
    // FROM-clause alias), so the client hydrates its `blocks_synced` staging
    // table and the JS observer materializes/decrypts into the app-visible
    // `blocks` table. The plain `FROM public.blocks` stream (row_type
    // `blocks`) that pre-Layout-B clients consumed has been dropped — those
    // clients no longer sync. The alias is REQUIRED: a bare `FROM public.blocks`
    // would surface row_type `blocks`, which the Layout B client has no raw
    // table for, so nothing would hydrate.
    table: 'public.blocks',
    as: 'blocks_synced',
    columns: BLOCK_STORAGE_COLUMNS,
    predicate: '        WHERE blocks_synced.workspace_id IN user_workspaces',
  },
] as const

const HEADER =
`# DO NOT EDIT — generated by scripts/gen-sync-config.ts.
# Run \`pnpm gen:sync-config\` after editing the column lists in
# src/data/blockSchema.ts or src/data/workspaceSchema.ts.
# CI runs \`pnpm check:sync-config\` to catch hand-edits.
#
# One auto-subscribed stream scoped to the requesting user's workspaces.
# Grouping the related tables into one stream keeps the client subscription
# surface and bucket count smaller than three independent auto streams.
# PowerSync re-evaluates the set whenever workspace_members changes.
#
# IMPORTANT: PowerSync derives the client-side row_type from the FROM-clause
# name. So a table whose row_type must match its name must NOT be aliased —
# \`FROM public.workspaces w\` would surface row_type='w' and a client would
# never hydrate its \`workspaces\` table. The DELIBERATE exception is the Layout B
# blocks stream: it aliases \`public.blocks AS blocks_synced\` precisely to
# re-emit \`blocks\` rows under row_type='blocks_synced', which the client stages
# and the JS observer materializes/decrypts into the app-visible \`blocks\` table.
# The pre-Layout-B plain \`FROM public.blocks\` stream (row_type='blocks') has been
# dropped at cutover — see the note on that query in gen-sync-config.ts.
#
# workspace_invitations is intentionally NOT synced. Invitations are queried
# on demand via Supabase REST + the workspace_invitations RLS policy keyed
# on auth.email(); putting the email claim into a sync rule would require
# threading the JWT through PowerSync's parameter system, and invitations
# are low-frequency events so polling on login is fine.

config:
  edition: 3

streams:
`

const renderQuery = ({ table, as, columns, predicate }: StreamQuery): string => {
  // The output name (alias if present, else the bare table name) drives BOTH
  // the client-side row_type and the column prefix, so an aliased query reads
  // `public.blocks AS blocks_synced` and projects `blocks_synced.<col>`.
  const outputName = as ?? table.replace(/^public\./, '')
  const projection = columns
    .map((c) => `          ${outputName}.${c.name}`)
    .join(',\n')
  const from = as ? `${table} ${as}` : table
  return `      - |
        SELECT
${projection}
        FROM ${from}
${predicate}
`
}

const renderStream = (): string => `  workspace_data:
    auto_subscribe: true
    with:
      user_workspaces: |
        SELECT workspace_id
        FROM public.workspace_members
        WHERE user_id = auth.user_id()
    queries:
${STREAM_QUERIES.map(renderQuery).join('')}
`

const generated = HEADER + renderStream()

const here = dirname(fileURLToPath(import.meta.url))
const targetPath = resolve(here, '..', 'powersync', 'sync-config.yaml')
const isCheck = process.argv.includes('--check')

const rel = relative(process.cwd(), targetPath)

if (isCheck) {
  const existing = existsSync(targetPath) ? readFileSync(targetPath, 'utf-8') : ''
  if (existing !== generated) {
    console.error(
      `❌ ${rel} is stale. Run \`pnpm gen:sync-config\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`✓ ${rel} is up to date.`)
} else {
  writeFileSync(targetPath, generated)
  console.log(`Wrote ${rel}.`)
}
